version: '3'

services:
  app:
    env_file:
      - .env
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      ENV: ${ENV}
      PORT: ${PORT}
      TF_CLIENT_ID: ${TF_CLIENT_ID}
      TF_CLIENT_SECRET: ${TF_CLIENT_SECRET}
      SECRET: ${SECRET}
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    restart: always
    image: mongo
    volumes:
      - ./data:/var/lib/mongodb/db
    ports:
      - "27017:27017"

volumes:
  node_modules:
